//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guifreaks.NavigationBar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignTimeText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignTimeText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guifreaks.NavigationBar.Resources.DesignTimeText", typeof(DesignTimeText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the Splitter..
        /// </summary>
        internal static string GradientSplitterSizeDesc {
            get {
                return ResourceManager.GetString("GradientSplitterSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text displayed in the header region..
        /// </summary>
        internal static string GroupViewCaptionDesc {
            get {
                return ResourceManager.GetString("GroupViewCaptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ContextMenuStrip associated with this control..
        /// </summary>
        internal static string GroupViewContextMenuStripDesc {
            get {
                return ResourceManager.GetString("GroupViewContextMenuStripDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines whether the control is expanded or collapsed to the header only..
        /// </summary>
        internal static string GroupViewExpandedDesc {
            get {
                return ResourceManager.GetString("GroupViewExpandedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height of the GroupView when it&apos;s expanded..
        /// </summary>
        internal static string GroupViewExpandedHeightDesc {
            get {
                return ResourceManager.GetString("GroupViewExpandedHeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shortcut menu to display when the user right-clicks the header. .
        /// </summary>
        internal static string GroupViewHeaderContextMenuStripDesc {
            get {
                return ResourceManager.GetString("GroupViewHeaderContextMenuStripDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height of the header..
        /// </summary>
        internal static string GroupViewHeaderHeightDesc {
            get {
                return ResourceManager.GetString("GroupViewHeaderHeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current height of the GroupView..
        /// </summary>
        internal static string GroupViewHeightDesc {
            get {
                return ResourceManager.GetString("GroupViewHeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the active button has been changed.
        /// </summary>
        internal static string NavigationBarActiveButtonChaningDesc {
            get {
                return ResourceManager.GetString("NavigationBarActiveButtonChaningDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently active button, returns null if none selected.
        /// </summary>
        internal static string NavigationBarActiveButtonDesc {
            get {
                return ResourceManager.GetString("NavigationBarActiveButtonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height (in pixels) of the visible buttons..
        /// </summary>
        internal static string NavigationBarButtonHeightDesc {
            get {
                return ResourceManager.GetString("NavigationBarButtonHeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The large image displayed when the button is not in compact mode..
        /// </summary>
        internal static string NavigationBarButtonLargeImageDesc {
            get {
                return ResourceManager.GetString("NavigationBarButtonLargeImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection containing the buttons of the NavigationBar..
        /// </summary>
        internal static string NavigationBarButtonsDesc {
            get {
                return ResourceManager.GetString("NavigationBarButtonsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image displayed when the button is in compact mode..
        /// </summary>
        internal static string NavigationBarButtonSmallImageDesc {
            get {
                return ResourceManager.GetString("NavigationBarButtonSmallImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the NavigationBar performs the layout of the buttons..
        /// </summary>
        internal static string NavigationBarPerformingButtonLayoutDesc {
            get {
                return ResourceManager.GetString("NavigationBarPerformingButtonLayoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the mouse is over the splitter and one of the buttons is down..
        /// </summary>
        internal static string NavigationBarSplitterMouseDownDesc {
            get {
                return ResourceManager.GetString("NavigationBarSplitterMouseDownDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the mouse is over the splitter..
        /// </summary>
        internal static string NavigationBarSplitterMouseMoveDesc {
            get {
                return ResourceManager.GetString("NavigationBarSplitterMouseMoveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user moved the splitter to a new location..
        /// </summary>
        internal static string NavigationBarSplitterMovedDesc {
            get {
                return ResourceManager.GetString("NavigationBarSplitterMovedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user is moving the splitter..
        /// </summary>
        internal static string NavigationBarSplitterMovingDesc {
            get {
                return ResourceManager.GetString("NavigationBarSplitterMovingDesc", resourceCulture);
            }
        }
    }
}
